version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
     - "3000:3000"
    volumes:
     - /file/node_modules
     - .:/file
  tests:
    build: .
    volumes:
     - /file/node_modules
     - .:/file
  web2:
    build: 
      context: .
      dockerfile: Dockerfile2.dev
    volumes:
     - /file/node_modules
     - .:/file
